const assert = require('assert')
const m = require('./main.js')
assert.strictEqual(m.report(5), 'loops:10 set:5')
assert.strictEqual(m.report(4), 'loops:6 set:4')
assert.strictEqual(m.report(1), 'loops:0 set:1')
assert.strictEqual(m.report(0), 'loops:0 set:0')
const src = require('fs').readFileSync('main.js', 'utf8')
assert.ok(/for\s*\(|while\s*\(/.test(src), 'count with loops')
assert.ok(/new\s+Set\b|\bSet\s*\(/.test(src), 'use a Set for the set path')
assert.ok(!/n\s*\*\s*\(\s*n\s*-\s*1\s*\)\s*\/\s*2/.test(src), 'do not hard-code the pair formula')
assert.ok(!/return\s+["'`]loops:\d/.test(src), 'build the report from counters, not a hard-coded string')

